org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Faster builds: reuse task outputs + run modules in parallel.
org.gradle.caching=true
org.gradle.parallel=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-17
